# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='l84', max_digits=8, null=True)),
                ('change', models.DecimalField(decimal_places=2, help_text='c63', max_digits=6, null=True)),
                ('change_perc', models.DecimalField(decimal_places=2, help_text='p43', max_digits=6, null=True)),
                ('market_cap', models.CharField(help_text='j10', max_length=12, null=True)),
                ('volume', models.BigIntegerField(help_text='v53', null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
