# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerHistorical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, help_text='l84', max_digits=8)),
                ('volume', models.BigIntegerField(help_text='v53', null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.Ticker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tickerhistorical',
            unique_together=set([('ticker', 'date')]),
        ),
    ]
